### ISSUE TITLE
[Bug] App crashes immediately after launch

### ISSUE THREAD

**Issue by collectorgeneral** [redfish64/TinyTravelTracker#38]
Downloaded the app today from F-Droid, tried launching it, but it crashes everytime right after launching the app (Gives the "Unfortunately, Tiny Travel Tracker has stopped." message) and keeps looping between launch and crash. The only way to quit is to force close the app. 

App details:
App version installed: V 1.1.7; Source: F-droid client.
Phone details:
Oneplus One (aka A0001 aka Bacon) running Cyanogen OS 13.1.1 (Android 6.0.1). 

Let me know if you need any additional details.

**Comment by redfish64** [comment]
Is this your first time running Tiny Travel Tracker, or have you been able
to successfully run prior versions?

Also, if you could get a stacktrace, that would be helpful (using "adb
logcat". Search for this term on Google if you don't know how to do this.)

I am only running Android 5, so this may be an Android 6 problem. I'll try
upgrading to see if I can reproduce this.

Downloaded the app today from F-Droid, tried launching it, but it crashes
everytime right after launching the app (Gives the "Unfortunately, Tiny
Travel Tracker has stopped." message) and keeps looping between launch and
crash. The only way to quit is to force close the app.

App details:
App version installed: V 1.1.7; Source: F-droid client.
Phone details:
Oneplus One (aka A0001 aka Bacon) running Cyanogen OS 13.1.1 (Android
6.0.1).

Let me know if you need any additional details.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/redfish64/TinyTravelTracker/issues/38>, or mute the
thread

**Comment by collectorgeneral** [comment]
> Is this your first time running Tiny Travel Tracker, or have you been able to successfully run prior versions?

This is my first time downloading and running the app. 

I have the logcat and I am copy-pasting relevant lines here (Though I do not know if I am removing other important details, let me know if that is the case):

08-16 22:20:08.163 25819 25854 E AndroidRuntime: FATAL EXCEPTION: Thread-1565

08-16 22:20:08.163 25819 25854 E AndroidRuntime: Process: com.rareventure.gps2, PID: 25819

08-16 22:20:08.163 25819 25854 E AndroidRuntime: Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}

08-16 22:20:08.163 25819 25854 E AndroidRuntime: java.lang.InternalError: Thread starting during runtime shutdown

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at java.lang.Thread.nativeCreate(Native Method)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at java.lang.Thread.start(Thread.java:1063)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:77)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:69)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:209)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at org.acra.util.HttpRequest.send(HttpRequest.java:133)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at org.acra.sender.HttpSender.send(HttpSender.java:245)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at org.acra.SendWorker.sendCrashReport(SendWorker.java:181)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at org.acra.SendWorker.checkAndSendReports(SendWorker.java:140)

08-16 22:20:08.163 25819 25854 E AndroidRuntime: 	at org.acra.SendWorker.run(SendWorker.java:76)

08-16 22:20:08.672  4607  4653 I chatty  : uid=1000(system) ActivityManager expire 11 lines

08-16 22:20:10.590 25868 25883 W ActivityThread: ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());

08-16 22:20:10.602  4607  4685 I chatty  : uid=1000(system) android.display expire 10 lines

08-16 22:20:11.805 25868 25905 E AndroidRuntime: FATAL EXCEPTION: main

08-16 22:20:11.805 25868 25905 E AndroidRuntime: Process: com.rareventure.gps2, PID: 25868

08-16 22:20:11.805 25868 25905 E AndroidRuntime: Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}

08-16 22:20:11.805 25868 25905 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.rareventure.gps2/com.rareventure.gps2.reviewer.map.OsmMapGpsTrailerReviewerMapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.rareventure.gps2.reviewer.map.OsmMapView.onDestroy()' on a null object reference

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3865)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3883)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.rareventure.gps2.reviewer.map.OsmMapView.onDestroy()' on a null object reference

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at com.rareventure.gps2.reviewer.map.OsmMapGpsTrailerReviewerMapActivity.onDestroy(OsmMapGpsTrailerReviewerMapActivity.java:1216)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:6422)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3852)

08-16 22:20:11.805 25868 25905 E AndroidRuntime: 	... 9 more

08-16 22:20:14.996 25923 25951 W ActivityThread: ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());

**Comment by redfish64** [comment]
The error is showing that a particular object, OsmMapView, which is
responsible for maps and uses native binary code (as opposed to java) is
not present when it should be, while it's trying to close the application.

It's really strange because it should be there at that time during the code
execution. But also I can't find anything about why the app is closing, so
I think the problem may be further up in the logcat log. It may be related
to the binary code associated with OsmMapView, which can fail in ways that
I am not so familiar with and that may be closing the app. So, if you can
get me more of the log file, earlier on, that should be helpful. The best
would be to start saving the log to a file, then start the app and have it
fail, so the file shows the complete log from startup.

If you are running adb logcat from a terminal or windows dos prompt (you
should be able to perform it this way):

1. Clear the existing log out of memory:

    adb logcat -c

2. Start logging to a file

    adb logcat > adb_log.txt

3. Run Tiny Travel Tracker and induce the error.

4. Hit control-c in the terminal.



In any case, I did update the code, and it should be available on F-Droid
tomorrow, v1.1.8, which will ignore the OsmMapView reference if it's not
present at that time. However, that doesn't explain why the app is closing,
but at least it gets us a little further on.


On Wed, Aug 17, 2016 at 10:38 PM, collectorgeneral <notifications@github.com

**Comment by collectorgeneral** [comment]
@redfish64 
Sorry, I wanted to provide you with the log initially, but I was not sure if I removed all my sensitive personal information. (Its been a really long time since I last used ADB). 

I did some checking on this log, it appears to be fine. Hopefully this will be useful. 
[20160817_TTT.txt](https://github.com/redfish64/TinyTravelTracker/files/423957/20160817_TTT.txt)

**Comment by redfish64** [comment]
Thanks for the effort.

The log shows it was just starting to display the welcome screen. So what
may be really happening is rather than the whole app being shutdown,
instead just the main activity window is being destroyed to display the
welcome screen. And, for some reason it looks like that is happening before
the init code of the main activity is finished running (which creates the
OsmMapView reference).

If that is the case, then v1.1.8 may fix it. It should be out tomorrow, you
can monitor the build log at the following link. It will be build 52:

https://f-droid.org/wiki/index.php?title=com.rareventure.gps2/lastbuild&redirect=no

**Comment by collectorgeneral** [comment]
@redfish64 
F-droid has updated its repos and I have installed the latest version, seems to solve the crashing issue! Thats great!
 
Have another issue though, closing this and reporting a separate instance, see #39 .
