### ISSUE TITLE
Lost the points info

### ISSUE THREAD

**Issue by fdroiduser** [redfish64/TinyTravelTracker#41]
Hi,

Since version 1.1.10, I can't "click" on the points anymore; before, I could select a zone, and see information inside that zone (when I came there, etc.)

I don't know if this is a bug on the latest version specifically on my phone, or a "feature" (i.e., a temporary removal of this functionality).
Without knowing what timestamp is associated with each point, the app loses its most important application :-)

Thanks!

**Comment by redfish64** [comment]
This was something I temporarily took out when I moved from the
discontinued mapquest tiles to mapzen vector tiles. I wasn't sure how well
the tangram library (which supports mapzen vector tiles) would work on
various devices that users own, so I wanted to release it as soon as
possible and get that worked out before getting anything other than the
core functionality done. Since converting point selection to tangram wasn't
trivial, I decided to leave that out in the first release with
tangram/mapzen.

I'm working on this now and it should be out within a few days, but no
promises :).

**Comment by redfish64** [comment]
This should be in version 1.1.11. You can monitor it here:
https://f-droid.org/wiki/index.php?title=com.rareventure.gps2/lastbuild&redirect=no
It will be builld 55

**Comment by redfish64** [comment]
fdroid just built it successfully.

**Comment by redfish64** [comment]
Closing.. please reopen if still an issue
