### ISSUE TITLE
Password timeout not working

### ISSUE THREAD

**Issue by licaon-kter** [redfish64/TinyTravelTracker#8]
1.0.13 from F-Droid on 5.1.1

I set up a timeout, even an hour, yet I'm asked for the password if i close the app (slide in the task manager yet the notification stays) or close the screen and unlock to the app.

Wasn't this meant for exactly these situations?
Also, after a while the password timeout resets to off, shouldn't it stay set up to one hour (or whatever) and reset the clock on a successful password enter so it does not lock for that time period hence forth?

Any ideas?

**Comment by redfish64** [comment]
I fixed the password timeout resetting to off. It will be in v1.0.14

TTT doesn't store the password to the SSD card ever, right now, only in memory. So if you close the app by sliding it out in the Task Manager, the password is removed along with it. 

I'm hesitant to save the password to the disk, because to me it seems like a security issue. I did a lot of work to make the GPS points encrypted all the time whenever they're written to the SSD card, and it seems kind of pointless to then store the unencrypted password on the SSD card alongside of them.

I am unable to reproduce the problem where you close the screen and it prompts for the password right away when you re-open it. Please try out v1.0.14, and let me know if you still have this issue.

After you've tried v1.0.14, if you still think that the password timeout should always work, then maybe I'll create an option such as "Full security / Weak Security / None" or something. In your case, you'd have to select "Weak Security" in order to make the password timeout always work. (I'd rather not complicate the interface by adding this, though).

On my phone, TTT stayed in memory as long as I didn't start some memory hogging game or something, so it didn't really seem like an issue.

**Comment by licaon-kter** [comment]
Tested a bit and works better, thanks.
